# Generated by Django 5.1.2 on 2024-11-01 18:02

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_manutenance', models.BooleanField(default=False, editable=False)),
                ('initial_hour_machine', models.FloatField(default=0, verbose_name='Initial Hour Machine')),
                ('initial_hour_suntech', models.FloatField(default=0, editable=False, verbose_name='Initial Hour Suntech')),
                ('worked_hours', models.FloatField(default=0, verbose_name='Worked Hours')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('model', models.CharField(blank=True, default='N/A', max_length=255, null=True, verbose_name='Model')),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='api.device')),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipment',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=100, verbose_name='Sobrenome')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Data de Contratação')),
                ('image', models.ImageField(blank=True, null=True, upload_to=api.models.get_file_path, verbose_name='Foto de Perfil')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='api.equipment', verbose_name='Equipamento')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_hour_suntech', models.FloatField(default=0, verbose_name='Initial Suntech Hour')),
                ('initial_hour_maintenance', models.FloatField(default=0, verbose_name='Initial Maintenance Hour')),
                ('worked_hours', models.FloatField(default=0, verbose_name='Worked Hours')),
                ('alarm_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('remaining_hours', models.FloatField(default=0, verbose_name='Remaining Hours')),
                ('name', models.CharField(max_length=255)),
                ('os', models.BooleanField(default=False)),
                ('obs', models.TextField(blank=True, null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='api.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceResetLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reset_date', models.DateTimeField(auto_now_add=True)),
                ('equipment_worked_hours', models.FloatField(default=0, verbose_name='Worked Hours Equipment')),
                ('maintenance_worked_hours', models.FloatField(default=0, verbose_name='Worked Hours Maintenance')),
                ('obs', models.TextField(blank=True, null=True)),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_logs', to='api.maintenance')),
            ],
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['device', 'name'], name='api_equipme_device__dea076_idx'),
        ),
    ]
